[engine]
    type = "scrapy"

[engine.settings]
LOG_LEVEL = 'INFO'
CONCURRENT_REQUESTS = 16
DOWNLOAD_DELAY = 0.2
PROXIES = [
    
    'http://mobi3:Infi2132@api.yourproxy.click:5103'
]
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'

[engine.settings.DOWNLOADER_MIDDLEWARES]
'salesnext_crawler.engines.scrapy.middleware.RandomizedProxyMiddleware' = 740

[engine.settings.DOWNLOAD_HANDLERS]
http = 'salesnext_crawler.engines.scrapy.downloader.curl_impersonate.CurlImpersonateDownloadHandler'
https = 'salesnext_crawler.engines.scrapy.downloader.curl_impersonate.CurlImpersonateDownloadHandler'

    [filesystems]

    [filesystems.local]
    type = 'LocalFileSystem'

    # List of storages
    [storages]

    [storages.video]
    type = 'pyarrow'
    format = 'parquet'
    filesystem = 'local'
    path = 'data/{crawler_id}/video/{chunk}.parquet'
    chunk_size = 1000

    [storages.channel]
    type = 'pyarrow'
    format = 'parquet'
    filesystem = 'local'
    path = 'data/{crawler_id}/channel/{chunk}.parquet'
    chunk_size = 1000

    [readers]

    [readers.channel]
    type = 'pyarrow'
    format = 'csv'
    filesystem = 'local'
    path = 'phone_table/*.csv'

    [readers.video]
    type = 'pyarrow'
    format = 'csv'
    filesystem = 'local'
    path = 'master_company_table/*.csv'


[crawler]
classname = 'sb_youtube_crawler.sb_youtube_crawler.SbYoutubeCrawler'